ipn_validate_endpoint : "https://www.sandbox.paypal.com/cgi-bin/webscr"
paypal_endpoint : "https://sandbox.paypal.com/cgi-bin/webscr?"
paypal_email : "bcaff86-facilitator@hotmail.com"

production:
  ipn_validate_endpoint : "https://www.paypal.com/cgi-bin/webscr"
  paypal_endpoint : "https://paypal.com/cgi-bin/webscr?"
  paypal_email : "bostonhhh@aol.com"
